### ISSUE TITLE
Update GroceryScreen

### ISSUE THREAD

**Issue by lauragoe** [OnlyLucas/software-engineering-project#18]
- [ ] Zusätzliche Funktion, ein Item "abzuhaken"

Erläuterung:
Für Historie brauchen wir einen Unterschied zwischen Löschen eines Items und dem Kaufen eines Items

**Comment by OnlyLucas** [comment]
Brauchen wir wirklich eine Historie für die Liste?

**Comment by lauragoe** [comment]
Sollte bei der Einkaufsliste nicht allzu viel Aufwand sein, von daher würden wir die gerne mit aufnehmen. Und ein weiterer "Abhak-Button" sollte vom UI ja auch machbar sein

**Comment by OnlyLucas** [comment]
Den Button habe ich hinzugefügt. Müssen uns überlegen wie wir jetzt das Backend umbauen damit das mit der Anzeige am Ende passt. Bis jetzt lädt er ja einfach alles was es in der Liste gibt, aber jetzt müssen wir das ja einschränken oder bin ich da falsch?

Habe auch noch in der ListScreenController.java eine Methode hinzugefügt für die Items "abzuhaken".

**Comment by lauragoe** [comment]
Also die "Liste" ist ja gerade nur ein Konstrukt, damit überhaupt was drin steht, eigentlich ist das ja ne Datenbanktabelle.
Da wird es das Attribut "is_completed" als boolean für jedes Einkaufsitem geben - das sollte somit einfach in der SQL-Anfrage umsetzbar sein.
