### ISSUE TITLE
Update Data Schema

### ISSUE THREAD

**Issue by N4ims** [OnlyLucas/software-engineering-project#27]
Group IDs are missing from some tables. As users can currently join multiple groups, we need to save in which group f.e. payments are made.

**Fix**
Either:
1) Add group IDs to the other tables
2) Change that one user can only join one group

**Comment by lauragoe** [comment]
Guter Punkt - ich würde Variante 1 nehmen, um es konstant zu halten.
Also bei den GroupGroceries haben wir das ja tatsächlich so gemacht, dass es die group als ID gibt und wir uns ja extra für die Tabelle GroupMembership entschieden haben, um die Mitgliedschaft in mehreren WGs (theoretisch) abbilden zu können

Hinzugefügt werden muss die group_id dann bei folgenden Tabellen verpflichtend: Cleaning, CleaningTemplate, Payment & PaymentsChange (auch wenn es nicht geändert werden kann, aber ist ja ne Kopie des Payments)
Und optional bei: PaymentParticipation (wie bei currency-code, dass es eigentlich am Payment hängt, aber von der Participation ausgelesen wird)
