### ISSUE TITLE
Budget Backend

### ISSUE THREAD

**Issue by lauragoe** [OnlyLucas/software-engineering-project#31]
- [x] Nach Monat gefilterte Payments (optional x Monate vom jetzigen Monat zurück)
-- ggf. Monat als Mapping-Key [WON'T BE ADDED]
- [x] Check/Filter Budget Inputs (Error when String as Amount Input)
- [x] Zusammenfassen von Payments und PaymentParticipation in einen Endpoint (@OneToMany)

**Comment by lauragoe** [comment]
- [x] Details Owe/Get Back
- [x] PaymentParticipations automatisch erstellen

**Comment by lauragoe** [comment]
- [x] Geldbeträge mit 2 Nachkommastellen
- [x] Jahr bei BudgetList mit anzeigen

**Comment by N4ims** [comment]
- [x] Set paidAt of PaymentParticipations when isPaid = true
- [x] Why? Some participations have a paidAt time set, although isPaid = false and they are not paid. How comes?

**Comment by lauragoe** [comment]
Offene Frage bezüglich mancher Einträge in DB, obwohl noch nicht paid siehe neues Issue #48
