### ISSUE TITLE
Consider Minor Updates to DB and Backend

### ISSUE THREAD

**Issue by N4ims** [OnlyLucas/software-engineering-project#36]
- [x] I think we should delete (or at least ignore) Currency Codes in the PaymentParticipation. As it is an effort to always consider that when updating participations and payments itself.
- [x] If we have a PaymentChange we should probably also have a PaymentParticipationChange
- [x] How are payment participations allocated in the frontend? Are the any options yet?
- [x] Add isExpired field to user
- [x] Should we add selections of users for the CleaningTemplate?
- [x] Rename column cleaning_template to cleaning_template_id

**Comment by lauragoe** [comment]
Wenn du eh an die DB gehst, bitte an allen Stellen das "interval" bei den CleaningTemplates abändern - habe da zumindest eben ne Fehlermeldung beim INSERT bekommen, und ChatGPT sagt, das sei ein weiters Keyword...

**Comment by lauragoe** [comment]
Changes können wir allgemein erstmal weglassen ;) Nicht Teil vom MVP, aber an sich stimmt es, dass die Participation dann auch geändert werden sollte

**Comment by lauragoe** [comment]
@N4ims bitte einmal Updates, was genau hiervon noch relevant ist bzw. lass uns mal gemeinsam drüber gehen

**Comment by N4ims** [comment]
Im DB schema könnten wir PaymentChanges durch PaymentParticipationChanges ersetzen. Die reichen aus, da die Nutzer ja am ehesten interessiert, ob sie plötzlich mehr bezahlen müssen. Und nicht das gesamte Payment. 

In der Implementation würde ich es noch nicht berücksichtigen und gegf, auch die Entities rauslöschen.

Selection of Users müssten wir halt mit Lukas und Meike eig. besprechen. Wäre nice, wenn es das gäbe, aber können es gerne auch rauslassen.

Die anderen die noch offen sind sollten denke ich noch erledigt werden.

**Comment by lauragoe** [comment]
Wir nutzen momentan allgemein keine PaymentChanges (also in keiner Abfrage, falls welche existieren). Von mir aus können wir die sonst auch komplett rauslöschen aus dem Schema, dann haben wir das mit den ParticipationChanges auch nicht.
Oder halt im Modell mit drin haben, dann aber keine Daten in der DB (sonst müssten wir die ja berücksichtigen)
