### ISSUE TITLE
UI Changes CleaningPlan

### ISSUE THREAD

**Issue by lauragoe** [OnlyLucas/software-engineering-project#42]
- [x] Feld für Datum des nächsten Cleanings bei der Übersicht der CleaningTemplates
- [x] Nach dem Klicken auf ein CleaningTemplate sollte der Name noch irgendwo zu sehen sein, welches Template man sich anschaut (Idee: Cleaning Plan im Header durch den Namen des CleaningTemplates ersetzen?)
- [x] Ist das "+" nach dem Anklicken oben rechts noch logisch bzw. soll man da auch noch ein neues Template anlegen können?
- [x] Daten eines Cleanings sollten abgehakt (und zusätzlich gelöscht) werden können
- [x] Layout CleaningDetailsList (Username, Datum der Cleanings)

**Comment by lauragoe** [comment]
- [x]  @Julikrebs  @OnlyLucas Neben dem Namen des geklickten CleaningTemplates sollte vielleicht ganz oben auch die Description zu sehen sein (sonst hat die bei der Eingabe ja gar keine Verwendung...)

**Comment by lauragoe** [comment]
- [x] Beim Add CleaningPlan hab ich Probleme, den DatePicker zu resetten wenn das Datum in der Vergangenheit liegt - habe euch mal ein TODO hinterlassen, vielleicht wisst ihr da mehr?

**Comment by Julikrebs** [comment]
> * [ ]  Beim Add CleaningPlan hab ich Probleme, den DatePicker zu resetten wenn das Datum in der Vergangenheit liegt - habe euch mal ein TODO hinterlassen, vielleicht wisst ihr da mehr?

Das musst du mir/uns mal zeigen. Bei mir ging es halt in meiner üblichen Geschwindigkeit und mit halb-funktionierendem Backend.
