### ISSUE TITLE
Hash User password while user creation.

### ISSUE THREAD

**Issue by N4ims** [OnlyLucas/software-engineering-project#46]

**Comment by lauragoe** [comment]
@N4ims schau bitte mal drüber, leider klappt der Endpoint im Backend noch nicht bzw. wirft beim BUILD nen Fehler wenn er nicht auskommentiert ist...

**Comment by N4ims** [comment]
Funktioniert.

Beispiel: {bcrypt}$2a$10$Q2rnSxxFRhNnli/S8ZzOZOsKpKG1rZplc0wBrKIJ9zUeuGSO3xXS.
