### ISSUE TITLE
AdapterCleaningPlanListDetailView Elemente mit Daten befüllen

### ISSUE THREAD

**Issue by Julikrebs** [OnlyLucas/software-engineering-project#49]
Anstelle des konkatenierten String, bitte die Elemente von AdapterCleaningPlanListDetailView einzeln befüllen. Die loadScreenElements-Methode ist fertig vorbereitet. Momentan Zeile 94.

**Comment by lauragoe** [comment]
- [x] Schriftgröße der neuen Description anpassen
- [x] ggf. zwei einzelne Elemente für Name und Description des Cleaning Templates? (momentan einfach mit : konkateniert

**Comment by Julikrebs** [comment]
Ich habe die neue Beschreibung theoretisch mit Daten befüllt, aber checkt das bitte nochmal, ob das hinhaut.
