### ISSUE TITLE
Open TODOs

### ISSUE THREAD

**Issue by lauragoe** [OnlyLucas/software-engineering-project#52]
- [x]     Todo rename params - FragmentBudgetMainController
- [x]             // TODO Add internationalization - CleaningTemplateRepository
- [x]             //TODO not shown - FragmentCleaningPlanAddController (jetzt wird "Select Date Range doch generell nicht mehr angezeigt...)
- [x] Allgemein deutsche Übersetzungen (ggf. auch Jonas?)

**Comment by OnlyLucas** [comment]
Was soll ich bei FragmentBudgetMainController umbenennen?

**Comment by lauragoe** [comment]
@OnlyLucas Weiß ich nicht, was ihr euch bei dem TODO gedacht habt (von mir stammt es zumindest nicht) - das Issue ist eher als Übersicht gedacht, welche noch so existieren
