### ISSUE TITLE
Add WG and add User to WG

### ISSUE THREAD

**Issue by lauragoe** [OnlyLucas/software-engineering-project#56]
- [x] Add user via mail
- [x] Fill Screen New Flat Share

**Comment by lauragoe** [comment]
@N4ims Man kann jetzt eine neue WG mit Name und Description hinzufügen. Theoretisch sollte das aber doch nur gehen, wenn man gerade noch keiner WG angehört, oder? Und sobald sie erstellt wurde, sollte die ja irgendwo als currentGroup gesetzt werden.

Können wir das momentan unterstützen oder lassen wir das einfach so?

**Comment by N4ims** [comment]
Ja, nur hinzufügen, wenn User noch keine WG hat. Dann können wir uns auch die Bestätigung sparen.

Gruppe zu current group hinzufügen kann ich beim Login machen. Setze du die bitte nach dem beitreten, wenn der User Beitritt

**Comment by lauragoe** [comment]
- [x] neue WG setzten wenn man eine erstellt
